apiVersion: apps/v1
kind: Deployment
metadata:
  name: Spark-Master
spec:
  selector:
    matchLabels:
      app: master
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
      - name: master
        image: daeyeonjoo/spark_master:2.4.4
        ports:
        - containerPort: 7077
        - containerPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Spark-Slave
spec:
  selector:
    matchLabels:
      app: slave
  template:
    metadata:
      labels:
        app: slave
    spec:
      containers:
      - name: slave
        image: daeyeonjoo/spark_slave:2.4.4
        ports:
        - containerPort: 7077
        - containerPort: 8080
        env:
        - MASTER_URL: spark://spark-master:7077





